package com.sati.model;
// Generated 25 sept. 2023, 20:35:19 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EtatInventaire generated by hbm2java
 */
@Entity
@Table(name = "etat_inventaire", catalog = "ismistock_bd")
public class EtatInventaire implements java.io.Serializable {

	private Integer idEtatInventaire;
	private String libEtatInventaire;
	private String codeTypeInventaitre;
	private Set<Point> points = new HashSet<Point>(0);

	public EtatInventaire() {
	}

	public EtatInventaire(String libEtatInventaire, String codeTypeInventaitre, Set<Point> points) {
		this.libEtatInventaire = libEtatInventaire;
		this.codeTypeInventaitre = codeTypeInventaitre;
		this.points = points;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_ETAT_INVENTAIRE", unique = true, nullable = false)
	public Integer getIdEtatInventaire() {
		return this.idEtatInventaire;
	}

	public void setIdEtatInventaire(Integer idEtatInventaire) {
		this.idEtatInventaire = idEtatInventaire;
	}
	
	@Column(name = "CODE_MATERIEL", length = 10)
	public String getCodeTypeInventaitre() {
		return codeTypeInventaitre;
	}

	public void setCodeTypeInventaitre(String codeTypeInventaitre) {
		this.codeTypeInventaitre = codeTypeInventaitre;
	}

	@Column(name = "LIB_ETAT_INVENTAIRE", length = 100)
	public String getLibEtatInventaire() {
		return this.libEtatInventaire;
	}

	public void setLibEtatInventaire(String libEtatInventaire) {
		this.libEtatInventaire = libEtatInventaire;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatInventaire")
	public Set<Point> getPoints() {
		return this.points;
	}

	public void setPoints(Set<Point> points) {
		this.points = points;
	}

}
