package com.sati.model;
// Generated 25 oct. 2023, 22:30:48 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EtatInventaire generated by hbm2java
 */
@Entity
@Table(name = "etat_inventaire", catalog = "sygep_bd")
public class EtatInventaire implements java.io.Serializable {

	private Integer idEtatInventaire;
	private String codeTypeInventaire;
	private String libEtatInventaire;
	private Set<Point> points = new HashSet<Point>(0);

	public EtatInventaire() {
	}

	public EtatInventaire(String codeTypeInventaire, String libEtatInventaire, Set<Point> points) {
		this.codeTypeInventaire = codeTypeInventaire;
		this.libEtatInventaire = libEtatInventaire;
		this.points = points;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_ETAT_INVENTAIRE", unique = true, nullable = false)
	public Integer getIdEtatInventaire() {
		return this.idEtatInventaire;
	}

	public void setIdEtatInventaire(Integer idEtatInventaire) {
		this.idEtatInventaire = idEtatInventaire;
	}

	@Column(name = "CODE_TYPE_INVENTAIRE", length = 10)
	public String getCodeTypeInventaire() {
		return this.codeTypeInventaire;
	}

	public void setCodeTypeInventaire(String codeTypeInventaire) {
		this.codeTypeInventaire = codeTypeInventaire;
	}

	@Column(name = "LIB_ETAT_INVENTAIRE", length = 20)
	public String getLibEtatInventaire() {
		return this.libEtatInventaire;
	}

	public void setLibEtatInventaire(String libEtatInventaire) {
		this.libEtatInventaire = libEtatInventaire;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etatInventaire")
	public Set<Point> getPoints() {
		return this.points;
	}

	public void setPoints(Set<Point> points) {
		this.points = points;
	}

}
