package com.sati.model;
// Generated 25 oct. 2023, 22:30:48 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Inventaire generated by hbm2java
 */
@Entity
@Table(name = "inventaire", catalog = "sygep_bd")
public class Inventaire implements java.io.Serializable {

	private Integer idInventaire;
	private String codeInventaire;
	private String libInventaire;
	private Date dateDebutInventaire;
	private Date dateFinInventaire;
	private Boolean etatCloture;
	private Set<Point> points = new HashSet<Point>(0);

	public Inventaire() {
	}

	public Inventaire(String codeInventaire, String libInventaire, Date dateDebutInventaire, Date dateFinInventaire,
			Boolean etatCloture, Set<Point> points) {
		this.codeInventaire = codeInventaire;
		this.libInventaire = libInventaire;
		this.dateDebutInventaire = dateDebutInventaire;
		this.dateFinInventaire = dateFinInventaire;
		this.etatCloture = etatCloture;
		this.points = points;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_INVENTAIRE", unique = true, nullable = false)
	public Integer getIdInventaire() {
		return this.idInventaire;
	}

	public void setIdInventaire(Integer idInventaire) {
		this.idInventaire = idInventaire;
	}

	@Column(name = "CODE_INVENTAIRE", length = 10)
	public String getCodeInventaire() {
		return this.codeInventaire;
	}

	public void setCodeInventaire(String codeInventaire) {
		this.codeInventaire = codeInventaire;
	}

	@Column(name = "LIB_INVENTAIRE", length = 15)
	public String getLibInventaire() {
		return this.libInventaire;
	}

	public void setLibInventaire(String libInventaire) {
		this.libInventaire = libInventaire;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_DEBUT_INVENTAIRE", length = 10)
	public Date getDateDebutInventaire() {
		return this.dateDebutInventaire;
	}

	public void setDateDebutInventaire(Date dateDebutInventaire) {
		this.dateDebutInventaire = dateDebutInventaire;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_FIN_INVENTAIRE", length = 10)
	public Date getDateFinInventaire() {
		return this.dateFinInventaire;
	}

	public void setDateFinInventaire(Date dateFinInventaire) {
		this.dateFinInventaire = dateFinInventaire;
	}

	@Column(name = "ETAT_CLOTURE")
	public Boolean getEtatCloture() {
		return this.etatCloture;
	}

	public void setEtatCloture(Boolean etatCloture) {
		this.etatCloture = etatCloture;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inventaire")
	public Set<Point> getPoints() {
		return this.points;
	}

	public void setPoints(Set<Point> points) {
		this.points = points;
	}

}
