package com.sati.model;
// Generated 25 oct. 2023, 22:30:48 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Point generated by hbm2java
 */
@Entity
@Table(name = "point", catalog = "ismistock_bd")
public class Point implements java.io.Serializable {

	private Integer idPoint;
	private EtatInventaire etatInventaire;
	private Inventaire inventaire;
	private Materiel materiel;
	private String observationPoint;
	private Date dateEnregPoint;
	private Integer manquantStock;

	public Point() {
	}

	public Point(EtatInventaire etatInventaire, Inventaire inventaire, Materiel materiel) {
		this.etatInventaire = etatInventaire;
		this.inventaire = inventaire;
		this.materiel = materiel;
	}

	public Point(EtatInventaire etatInventaire, Inventaire inventaire, Materiel materiel, String observationPoint,
			Date dateEnregPoint, Integer manquantStock) {
		this.etatInventaire = etatInventaire;
		this.inventaire = inventaire;
		this.materiel = materiel;
		this.observationPoint = observationPoint;
		this.dateEnregPoint = dateEnregPoint;
		this.manquantStock = manquantStock;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_POINT", unique = true, nullable = false)
	public Integer getIdPoint() {
		return this.idPoint;
	}

	public void setIdPoint(Integer idPoint) {
		this.idPoint = idPoint;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_ETAT_INVENTAIRE", nullable = false)
	public EtatInventaire getEtatInventaire() {
		return this.etatInventaire;
	}

	public void setEtatInventaire(EtatInventaire etatInventaire) {
		this.etatInventaire = etatInventaire;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_INVENTAIRE", nullable = false)
	public Inventaire getInventaire() {
		return this.inventaire;
	}

	public void setInventaire(Inventaire inventaire) {
		this.inventaire = inventaire;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_MATERIEL", nullable = false)
	public Materiel getMateriel() {
		return this.materiel;
	}

	public void setMateriel(Materiel materiel) {
		this.materiel = materiel;
	}

	@Column(name = "OBSERVATION_POINT")
	public String getObservationPoint() {
		return this.observationPoint;
	}

	public void setObservationPoint(String observationPoint) {
		this.observationPoint = observationPoint;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_ENREG_POINT", length = 19)
	public Date getDateEnregPoint() {
		return this.dateEnregPoint;
	}

	public void setDateEnregPoint(Date dateEnregPoint) {
		this.dateEnregPoint = dateEnregPoint;
	}

	@Column(name = "MANQUANT_STOCK")
	public Integer getManquantStock() {
		return this.manquantStock;
	}

	public void setManquantStock(Integer manquantStock) {
		this.manquantStock = manquantStock;
	}

}
