package com.sati.model;
// Generated 25 oct. 2023, 22:30:48 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reparation generated by hbm2java
 */
@Entity
@Table(name = "reparation", catalog = "sygep_bd")
public class Reparation implements java.io.Serializable {

	private Integer idReparation;
	private Materiel materiel;
	private String code;
	private Date dateMiseReparation;
	private String descriptionPanne;
	private Date dateRetourService;

	public Reparation() {
	}

	public Reparation(Materiel materiel) {
		this.materiel = materiel;
	}

	public Reparation(Materiel materiel, String code, Date dateMiseReparation, String descriptionPanne,
			Date dateRetourService) {
		this.materiel = materiel;
		this.code = code;
		this.dateMiseReparation = dateMiseReparation;
		this.descriptionPanne = descriptionPanne;
		this.dateRetourService = dateRetourService;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_REPARATION", unique = true, nullable = false)
	public Integer getIdReparation() {
		return this.idReparation;
	}

	public void setIdReparation(Integer idReparation) {
		this.idReparation = idReparation;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_MATERIEL", nullable = false)
	public Materiel getMateriel() {
		return this.materiel;
	}

	public void setMateriel(Materiel materiel) {
		this.materiel = materiel;
	}

	@Column(name = "CODE", length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_MISE_REPARATION", length = 10)
	public Date getDateMiseReparation() {
		return this.dateMiseReparation;
	}

	public void setDateMiseReparation(Date dateMiseReparation) {
		this.dateMiseReparation = dateMiseReparation;
	}

	@Column(name = "DESCRIPTION_PANNE", length = 65535)
	public String getDescriptionPanne() {
		return this.descriptionPanne;
	}

	public void setDescriptionPanne(String descriptionPanne) {
		this.descriptionPanne = descriptionPanne;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_RETOUR_SERVICE", length = 10)
	public Date getDateRetourService() {
		return this.dateRetourService;
	}

	public void setDateRetourService(Date dateRetourService) {
		this.dateRetourService = dateRetourService;
	}

}
